### PR TITLE
`filter_missing` flag

### LINKED ISSUE #90: Filter out samples with missing values
@valentynbez created a PR https://github.com/qiime2/q2-composition/pull/82 which supports this feature, however we really want to create a new flag, such as: `filter_missing: bool = False` which, when true, would not raise an error when samples have missing values in their metadata, instead filtering them out.

As @valentynbez mentions:
> 
> During the analysis, I had some missing metadata values. To counter it I had to:
> 
>     revert to a feature-table step
>     filter it, filter than collapse it
>     add_pseudocount
>     filter metadata
>     finally run ancom
> 
> Missing values in metadata are human-introduced errors, they appear quite often. This is an inconvenient workflow for the user.

General behavior and tests are already written in the above PR, we just need to adapt it to use a flag instead of always filtering.
(Please rebase the commit history such that it includes their commit(s) if you adapt the above PR, that way @valentynbez get's proper attribution.)

### PR DESCRIPTION
**Pull request by valentynbez**
- if `True` filters samples with missing metadata
- if `False` raises en error informing user about missing values
- tests
- test code refractor
- closes #90

### CODE REVIEW

**Comment by valentynbez** [comment]
Not sure what is happening, the command `py.test --pyargs q2_composition` runs on my machine without errors

**Comment by lizgehret** [comment]
Thanks for implementing these changes @valentynbez! I've fixed the merge conflicts and removed the logging (QIIME 2 doesn't have the ability to utilize that) - I think there is a small test failure just due to regex matching, but I'll pull this down locally and test on my end to confirm. Otherwise this should be good to go!

**Comment by valentynbez** [comment]
Thanks for looking into it!

**Comment by lizgehret** [comment]
I added one small fix just on the ID sorting in your error branch, but this is otherwise good to go! Thanks @valentynbez 🙂

**Pull request merged**
