### PR TITLE
Revert "Downgrade pandas to <0.23 instead of >=0.23"

### PR DESCRIPTION
**Pull request by ebolyen**

### CODE REVIEW

**Comment by mortonjt** [comment]
Wait. Why? Aren't we trying to upgrade the dependencies?

**Comment by ebolyen** [comment]
Yep :) it's a revert of a version pin.

**Comment by ebolyen** [comment]
Actually @mortonjt, would you mind reviewing this real quick? The pandas API changes pretty significantly between the last pin and 0.23, so I think the retains the same behavior (and the plot certainly looks right).

**Comment by mortonjt** [comment]
Oh. Awesome!

**Comment by thermokarst** [comment]
Travis is out of commission for now, tested locally.

**Pull request merged**
