### PR TITLE
rename ancombc -> ancombc2

### PR DESCRIPTION
**Pull request by colinbrislawn**
WIP, do not merge.

Simple change to method name to address warning.

This looks like an extension/improvement to `ancombc` function, but let's see if tests pass.
https://github.com/FrederickHuangLin/ANCOMBC/blob/devel/R/ancombc2.R

### CODE REVIEW

**Comment by colinbrislawn** [comment]
>    unused arguments (formula = formula, tol = tol, max_iter = max_iter, conserve = conserve)

formula ->fix_formula 
tol and max_iter ->`iter_control = list(tol = tol, max_iter = max_iter, verbose = FALSE)`
conserve is not used in ancombc2(). Looks like this is built into the new function?
>#' @param conserve logical. whether to use a conservative variance estimator for
#' the test statistic. It is recommended if the sample size is small and/or
#' the number of differentially abundant taxa is believed to be large.
#' Default is FALSE.

**Comment by colinbrislawn** [comment]
>  Error in `colnames<-`(`*tmp*`, value = "id") : 
    attempt to set 'colnames' on an object with less than two dimensions

Looks like  `fit` object returned by ancombc2() may be different.

**Comment by ebolyen** [comment]
Hey @colinbrislawn, yeah we realized pretty early that ancombc2 was not a drop-in replacement for ancombc, so we just finished work on adding ancombc and still need to do some exploration here for ancombc2.

cc @lizgehret

**Comment by lizgehret** [comment]
@colinbrislawn yeah echoing what @ebolyen mentioned above - these two methods are actually quite different. From the README in Huang's ANCOMBC repository, it looks like ANCOM-BC2 has a manuscript in preparation, so we had discussed waiting until there was a publication before adding this new method in.

**Comment by lizgehret** [comment]
Hey @colinbrislawn are you okay if we close this one out? Once a paper is published for ancombc2, we'll definitely look into adding that as another method in composition, but I don't know if this PR makes sense to keep open since it's not just a drag and drop replacement for ancombc.

**Comment by colinbrislawn** [comment]
Yes, I agree that a holistic PR is needed once we are ready.

**Pull request closed without merging**
