### PR TITLE
Ancom w testing

### PR DESCRIPTION
**Pull request by antonhibl**
Added a ancom_w method to q2-composition which helps users pull w-scores specifically out of ancom statistical data to be used with software and plugins like Qurro.

cc @ebolyen

### CODE REVIEW

**Comment by ebolyen** [comment]
Hey @mortonjt,

We set up what we thought would be a pretty simple 3-category test of ANCOM (the original w one), but we're not getting quite what we expect ([test case](https://github.com/qiime2/q2-composition/pull/78/files#diff-cb62f920b483e9dfe9a90a149872a3ff8abc897433e122a3fedc25440f8522ecR203-R222), [test failure](https://github.com/qiime2/q2-composition/runs/3223151775)).

It's a matrix of 10's and 0's with 2 missing taxa unique to each group, and two samples with identical observations. We anticipated that this should be a W-score of 4, since there were 6 samples, and the samples with identical observations should fail the pairwise tests, but we're getting 5.

What are we missing?

**Comment by mortonjt** [comment]
I’m afaik at the moment, probably will want to check all pairwise tests to
see if they are working as expected.
Although I’d recommend double checking if the 2 category test works first.

**Comment by mortonjt** [comment]
Alright, so it looks like its your f-test that is actually is the source of the problem.

Your F-test is boils down to computing the (across group variance) / (within group variance).  And since your within group variance is zero, your F-statistic is going to shoot into infinity.

The easy way around this is to add a little bit of jitter to your tables.

If you run 
```python
t += np.abs(random.randn(6, 6)) * 0.1
res = ancom(t, md)
```
You will get output that is closer to what you are expecting.

**Comment by ebolyen** [comment]
That explains it perfectly, thanks @mortonjt! We'll get this test straightened out.

Relatedly, how do you feel about creating this method (tentatively `ancom-w`) which returns just the FeatureData[Differential] type? We've been playing around with Qurro recently and think it could pretty reasonably replace the volcano plot in the future, since Qurro is basically already that, just sideways and with bars instead of points.

**Comment by mortonjt** [comment]
I think the `ancom-w` method is a nice idea -- it isn't the same type of differential, but it could help facilitate qurro.
This will especially become more relevant for newer versions of ANCOM that do report log-fold changes.

**Comment by ebolyen** [comment]
Yeah I was a little uncertain on the type here. Differential is really more for coefficients right?

Any suggestions on type names? We could use "importances" from q2-sample-classifier and update Qurro to use that, but ironically, I think turning importances into the differential type might make more sense, which still leaves ancom-w without a good output type.

**Comment by mortonjt** [comment]
When I use `Differential`, I'm explicitly referring to vector quantities that are directly proportional to log-fold changes. 
Songbird, ALDEx2, DESeq2, edgeR, limma and later versions of ANCOM all return this quantity.

From a semantic point of view, I think it makes a lot of sense to restrict `Differential` to only log-fold changes. I don't know the best approach with the old version of ANCOM to be honest.

**Comment by ebolyen** [comment]
Hypothetical proposal:

1. We move `FeatureData[Importance]` to from q2-sample-classifier to q2-types
2. We annotate the output of this method to be `FeatureData[Importance]` instead of `Differential`
3. We update Qurro to accept `FeatureData[Differential | Importance]`

I think that would work, since the balance behavior of Qurro appears independent of the vectors, as are the boxplots. So I don't think we would break any assumptions in Qurro necessarily, and then `Differential` is kept clean for downstream use of the log ratios.

cc @nbokulich

**Comment by mortonjt** [comment]
In principle I am ok with this, but we'll probably want to add additional documentation somewhere (i.e. qurro) to clarify these types.  For instance, there is no reason to believe that feature importances would lead to meaningful log-ratios (where as differentials have theoretical justification).

cc @fedarko

**Comment by nbokulich** [comment]
I agree with @mortonjt on this — but otherwise in principle I am fine with your proposal @ebolyen particularly points 1 and 3. It would be neat to use qurro downstream of e.g., q2-sample-classifier.

**Comment by fedarko** [comment]
All sounds fine to me. I'm happy these tools are still useful!

> I think that would work, since the balance behavior of Qurro appears independent of the vectors, as are the boxplots. So I don't think we would break any assumptions in Qurro necessarily, and then Differential is kept clean for downstream use of the log ratios.

Yeah, this shouldn't pose a problem (at least from what I can remember). Qurro does some basic validation on the feature rankings DataFrame, but I imagine this shouldn't be a problem for the importance scores -- it's more along the lines of "are there at least two features and one column in this DF", "are any of the numbers in this DF so ridiculously large that they can't be safely represented in JavaScript", etc.

One minor issue worth bringing up re: point 3 in @ebolyen's proposal is that we have two ways of modifying Qurro to accept these importance scores. We could either:

  1) modify `qiime qurro differential-plot` to accept `FeatureData[Differential | Importance]`, or
  2) add a new visualizer to Qurro named `qiime qurro importance-plot` or something that just accepts `FeatureData[Importance]`.

I'm fine with either approach, although if we opt for the first one than we probably want to modify the visualizer name from `differential-plot` to just `vector-plot` or something similar.

> In principle I am ok with this, but we'll probably want to add additional documentation somewhere (i.e. qurro) to clarify these types. For instance, there is no reason to believe that feature importances would lead to meaningful log-ratios (where as differentials have theoretical justification).

It's worth noting that the reliance on the term "Differential" referring to log-fold changes is already broken in some places. For example, the table of results returned by ALDEx2 (at least when run through R, the q2-aldex2 plugin likely works differently) includes stuff like p-values. The (albeit non-QIIME-2) Qurro + ALDEx2 tutorial @gibsramen and I set up last year includes [a note explaining this to the reader](https://nbviewer.jupyter.org/github/biocore/qurro/blob/master/example_notebooks/ALDEx2_TCGA_LUSC/transcriptomic_example.ipynb#6.1.1.1.-Some-notes-about-ALDEx2-outputs,-and-the-term-Differential), which we could probably generalize and add to Qurro's README or something.

**Comment by lizgehret** [comment]
Hey @ebolyen do we want to get this one merged?

**Pull request closed without merging**
